### ISSUE TITLE
Arcanum 2.0 lose on time

### ISSUE THREAD

**Issue by toni-chess** [LarsAur/Arcanum#9] opened 2024-05-11 21:52 UTC
Thanks for sharing Arcanum!
Arcanum  1.12 works fine but Arcanum 2.0 lose on time!

GUI: Arena 3.5.1
OS: Windows 10 Pro
TimeControl: 10s+0.1 per game

**Comment by LarsAur** [comment] 2024-05-11 23:01
Thank you for taking your time to report the issue, and the concise description. I will look into it :)

**Comment by LarsAur** [comment] 2024-05-12 15:07
Hi, I have added some changes to time allocation to avoid losing on time.

While I have tested it myself, it would be nice to have confirmation that it works for you as well 😄 
The changes are available in the branch linked to the issue.
If you do not want to compile the changes for yourself, you could use this one built by me: 
[Arcanum-TimeAllocation.zip](https://github.com/LarsAur/Arcanum/files/15286724/Arcanum-TimeAllocation.zip)

Edit: I have also added a MoveOverhead uci option, which is set to 10 by default.

**Comment by toni-chess** [comment] 2024-05-12 23:27
Thank you so much for your speedy reply!!
I can't compile Arcanum, so I will test your build.

**Comment by toni-chess** [comment] 2024-05-13 21:49
Hi There!
I tested Arcanum 2.0 vs 70 other engines simular strength based on Arcanum 1.12 +150 Elo. 
TimeControl: 9s+0.1s

[Arcanum 2.0 x64]
Hash=16
NNUEPath=arcanum-net-v2.fnnue
SyzygyPath=%ArenaDrive%\Chess\Syzygy
MoveOverhead=10

After 840 games Arcanum 2.0 is almost 200 Elo weaker than Arcanum  1.12 !!!!!!
Arcanum 2.0 does not lose on time any more, only 3-4 games make illegal move!
Thank you!
Sory for my english.

**Comment by LarsAur** [comment] 2024-05-13 22:43
Wow that was alot more testing than i anticipated! Thank you so much!

Just to be clear, when you say you have tested Arcanum 2.0. Do you refer to the version i sent previously in this issue, or the actual 2.0 release?

If this version is 200 ELO weaker than Arcanum 1.12, i would assume something is very wrong. The version i sent, contains a new NNUE net which is not compatible with the 2.0 release, only with the version i sent here. Could this be the issue?

As soon as i get the time, I shall double check that the version i sent you is not faulty. 

Edit: The reason why I suspect something i wrong, is that my tests at 60s+0.5s suggests that Arcanum 2.0 should be about 200 Elo stronger than 1.12. And the version I sent here should again be about 150-200 Elo stronger than the 2.0 release.

The illegal moves might be a bit concerning. Are you able to see which illegal moves are made?  For example, the move a1a1 could indicate that it did not have time to search any moves, thus returning a null move.

If you have the PGNs with the illegal moves, it would be great if you could send them here.

Again, thank you so much for testing and giving feedback :)

**Comment by toni-chess** [comment] 2024-05-14 07:13
I tested the version you  sent to me previously (https://github.com/LarsAur/Arcanum/files/15286724/Arcanum-TimeAllocation.zip)
As you see on Arcanum settings i use new NNUE(arcanum-net-v2.fnnue)

You can see more info on files i sent below.
https://drive.google.com/file/d/1K7JHOrvR0gAd3QCK4lY-wXNvoEEQ_qyc/view?usp=sharing
have a good time!

**Comment by LarsAur** [comment] 2024-05-14 07:26
Thank you. I will look into it :)

**Comment by LarsAur** [comment] 2024-05-15 23:04
Hi again,

I believe I have manged to identify the cause of the illegal moves. It seems to be a mix between an issue in Arcanum, and in Arena Chess GUI.

It seems like if there is something causing Arena to lag, the additional time is subtracted from the engines time.
This seems to be especially prevalent if the debug window is open, as it requires some time to print the messages. Because of this, the engine and the GUI disagrees on how much time is used (Maybe there is an issue with my setup?). While the engine does not necessarily time out, the time might be set to 1ms (or stopped by UCI stop). Arcanum then had an issue where if for some reason it did not have enough time to evaluate any moves, an illegal null move (a1a1) was returned.

I have found a solution to the problem in Arcanum, which is to just return the first generated move. I ran 400 games of 2s + 0.1s playing against itself in Arena, and I no longer get these illegal moves. 

It might also be an idea to increase the MoveOverhead in Arena, as I have not encountered this issue in CuteChess, and it is of course not ideal to return the first move.

For the issue regarding the performance, I am not sure what the issue is, as stated previously, when I play Arcanum 1.12 against 2.0, 2.0 is clearly much stronger.

I will close the issue for now, however please reopen it or create a new one if you encounter any problems :)

**Comment by toni-chess** [comment] 2024-05-24 05:45
Hi again!

I retested Arcanum on Arena and Cuteshess too. 
Arcanum 1.12 is much stronger than Arcanum 2.0 and Arcanum 2.1.
below are the results:

Arena Test:
   Engine                    Score 
1: Arcanum 1.12 x64(AVX2) 179.5/200
2: Arcanum 2.0 x64(AVX2)    60.5/200
3: Arcanum 2.1 x64(AVX2)    60.0/200

Cutechess Test:
1 | Arcanum 1.12 x64(AVX2-5Pct)  | 150,0 | 200 |
2 | Arcanum 2.1 x64(AVX2-5Pct)    |   80,0 | 200 |
3 | Arcanum 2.0 x64(AVX2-5Pct)    |   70,0 | 200 |

**Comment by LarsAur** [comment] 2024-05-24 07:15
Hi again :)

What configurations are you using for v1.12?

If nnue is enabled for v1.12, it uses a stockfish net, which is removed in v2.0 and v2.1. While the SF net is likely stronger, I did not want to keep using a net not generated by me.

The improvements reported in the v2.0 and v2.1release is thus based on using HCE (not nnue) for v1.12 and using the new selfmade nets for v2.0 and v2.1

Could this be the issue?

**Comment by toni-chess** [comment] 2024-05-24 11:40
[Arcanum 2.1 x64(AVX2)]
Hash=16
NNUEPath=arcanum-net-v2.fnnue.fnnue
SyzygyPath=%ArenaDrive%\Chess\Syzygy
MoveOverhead=10

[Arcanum 2.0 x64(AVX2)]
Hash=16
NNUEPath=arcanum-net-v2.fnnue
SyzygyPath=%ArenaDrive%\Chess\Syzygy
MoveOverhead=10

[Arcanum 1.12 x64(AVX2)]
Hash=16
UseNNUE=true
HCEWeightFile=hceWeights.dat

Yes you are right
 NNUE is enabled for Arcanum 1.12, so it uses the stockfish net: nn-04cf2b4ed1da.nnue

**Comment by LarsAur** [comment] 2024-05-27 20:20
Sorry for getting back to you so late. As I understand it, this solved the issue/misunderstanding.

Thanks for reporting it, always fun to know someone is testing the engine :)

Btw, I am not sure how well *arcanum-net-v2.fnnue* works with v2.0 (I have not tested it).
The feature transformer changed somewhat between v2.0 and v2.1. Thus it is likely better to use *arcanum1.fnnue* with v2.0 and *arcanum-net-v2.fnnue* with v2.1.

**Closed as completed by LarsAur** 2024-05-27 20:20 UTC
